resolver: lts-12.17
packages:
- '.'
flags: {}
extra-deps:
  - conduit-1.3.1
  - conduit-extra-1.3.0
  - bytestring-0.10.8.2
  - async-2.2.1
  - Cabal-2.2.0.1
  - directory-1.3.1.5
extra-package-dbs: []
